DROP INDEX IF EXISTS idx_short_url;
DROP INDEX IF EXISTS idx_original_url_unique;
DROP TABLE IF EXISTS urls CASCADE;

DROP INDEX IF EXISTS idx_users_id;
DROP INDEX IF EXISTS idx_username_unique;
DROP TABLE IF EXISTS users CASCADE;