// Code generated by reset.go; DO NOT EDIT.

package model

func (s *AuditEntity) Reset() {
	s.Ts = 0
}

func (s *URLCreateRequestWithoutUser) Reset() {
	s.OriginalURL = ""
}

func (s *URLCreateRequest) Reset() {
	s.OriginalURL = ""
}

func (s *URLCreate) Reset() {
	s.OriginalURL = ""
}

func (s *URLCreateResponse) Reset() {
	s.ID = ""
}

func (s *GetByShortURLResponse) Reset() {
	s.OriginalURL = ""
}

func (s *URLEntity) Reset() {
	s.OriginalURL = ""
}

func (s *URLListEntity) Reset() {
	s.OriginalURL = ""
}

func (s *URLBulkCreateRequestWithoutUser) Reset() {
	s.CorrelationID = ""
}

func (s *URLBulkCreateRequest) Reset() {
	s.CorrelationID = ""
}

func (s *URLBulkCreate) Reset() {
	s.CorrelationID = ""
}

func (s *URLBulkCreateResponse) Reset() {
	s.CorrelationID = ""
}

func (s *URLNestedData) Reset() {
	s.OriginalURL = ""
}

func (s *URLUpdateResponse) Reset() {
	s.OriginalURL = ""
}

func (s *URLDelete) Reset() {
	s.ShortURL = ""
}

func (s *User) Reset() {
	s.ID = 0
}
