package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

var defaultTypes = []string{
	"bool", "string", "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32",
	"uint64", "uintptr", "byte", "float32", "float64", "interface{}", "error",
}

type FieldInfo struct {
	Name         string
	DefaultValue string
}

type StructInfo struct {
	StructName string
	Fields     []FieldInfo
}

type StructData struct {
	GenDecl *ast.GenDecl
	Data    *ast.StructType
}

type TemplateData struct {
	PackageName string
	Structs     []StructInfo
}

const resetTemplate = `// Code generated by reset.go; DO NOT EDIT.

package {{.PackageName}}

{{range .Structs}}
func (s *{{.StructName}}) Reset() {
	{{- range .Fields}}
	{{.DefaultValue}}
	{{- end}}
}
{{end}}
`

func main() {
	var dir string
	fs := flag.NewFlagSet("fs", flag.ExitOnError)
	fs.StringVar(&dir, "dir", ".", "absolute path to the directory")
	err := fs.Parse(os.Args[1:])
	if err != nil {
		log.Fatal(err)
	}
	envDir, ok := os.LookupEnv("DIR")
	if ok {
		dir = envDir
	}
	absDirPath, err := filepath.Abs(dir)

	if err != nil {
		log.Fatal(fmt.Errorf("failed to get absolute path: %v\n", err))
	}

	if _, err = os.Stat(absDirPath); os.IsNotExist(err) {
		log.Fatal(fmt.Errorf("directory does not exist: %s\n", absDirPath))
	}

	err = processDirectory(absDirPath)
	if err != nil {
		log.Fatal(fmt.Errorf("error: %v\n", err))
	}
}

// processDirectory goes through .go files to extract and process structs with the comment `// generate:reset`.
func processDirectory(dir string) error {
	var structsToProcess []StructData
	var pkgName string
	var pathToWrite string
	var pkgStructs = make(map[string]struct {
		PkgName string
		Structs []StructData
	})
	var resettableStructs []string

	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return fmt.Errorf("failed to walk through directory: %s, err: %v\n", path, err)
		}

		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			log.Printf("failed to read file: %s,  err: %v\n", path, err)
			return nil
		}
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, content, parser.ParseComments)
		if err != nil {
			log.Printf("failed to parse file: %s, err: %v\n", path, err)
			return nil
		}

		if file.Name != nil {
			if pkgName != file.Name.Name {
				structsToProcess = []StructData{}
			}
			pkgName = file.Name.Name
			splitDir := strings.Split(path, "/")
			pathToWrite = strings.Join(splitDir[0:len(splitDir)-1], "/")

			fileStructs := lookForStructs(file)

			if len(fileStructs) > 0 {
				for _, s := range fileStructs {
					structsToProcess = append(structsToProcess, s)
				}
				for _, s := range fileStructs {
					resettableStructs = append(resettableStructs, s.GenDecl.Specs[0].(*ast.TypeSpec).Name.Name)
				}

				curPkg, ok := pkgStructs[pkgName]
				if !ok {
					pkgStructs[pathToWrite] = struct {
						PkgName string
						Structs []StructData
					}{PkgName: pkgName, Structs: structsToProcess}
				} else {
					curPkg.Structs = append(pkgStructs[pathToWrite].Structs, fileStructs...)
				}
			}
		}
		return nil

	})

	if err != nil {
		return fmt.Errorf("failed to walk through files error: %v\n", err)
	}

	for path, data := range pkgStructs {
		processedStructs := setDefaultValue(data.Structs, resettableStructs)
		err = createFile(path, data.PkgName, processedStructs)
		if err != nil {
			return fmt.Errorf("failed to create file: %s, err: %v\n", path, err)
		}
	}

	return nil
}

// lookForStructs search for structs with the comment `// generate:reset`.
func lookForStructs(file *ast.File) []StructData {
	var resettableStructs []StructData
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			if genDecl.Doc != nil {
				for _, comment := range genDecl.Doc.List {
					if comment.Text == "// generate:reset" {
						resettableStructs = append(resettableStructs, struct {
							GenDecl *ast.GenDecl
							Data    *ast.StructType
						}{GenDecl: genDecl, Data: structType})
					}
				}
			}
		}
	}
	return resettableStructs
}

// setDefaultValue sets a default value to a field according to its type.
func setDefaultValue(structs []StructData, resettableStructs []string) []StructInfo {
	var result []StructInfo
	for _, s := range structs {
		var fields []FieldInfo
		if s.Data.Fields != nil && s.Data.Fields.List != nil {
			for _, field := range s.Data.Fields.List {
				for _, name := range field.Names {
					defaultValue := getFieldStatement(field, resettableStructs)
					fields = append(fields, FieldInfo{
						Name:         name.Name,
						DefaultValue: defaultValue,
					})
				}
				break
			}
			result = append(result, StructInfo{
				StructName: s.GenDecl.Specs[0].(*ast.TypeSpec).Name.Name,
				Fields:     fields,
			})
		}
	}
	return result
}

// getFieldStatement generates statement for a field.
func getFieldStatement(field *ast.Field, resettableStructs []string) string {
	var typeName string
	switch v := field.Type.(type) {
	case *ast.Ident:
		typeName = v.Name
		defaultValue := getDefaultValue(typeName)
		return fmt.Sprintf("s.%s = %s", field.Names[0].Name, defaultValue)
	case *ast.StarExpr:
		switch v.X.(type) {
		case *ast.SelectorExpr:
			sel := v.X.(*ast.SelectorExpr).Sel.Name
			x := v.X.(*ast.SelectorExpr).X.(*ast.Ident).Name
			return fmt.Sprintf("if s.%s != nil {\n    *s.%s = %s.%s{}}", field.Names[0].Name, field.Names[0].Name, x, sel)
		case *ast.Ident:
			x := v.X.(*ast.Ident).Name
			for _, r := range resettableStructs {
				if r == x {
					return fmt.Sprintf("s.Reset()")
				}
			}
			for _, t := range defaultTypes {
				if t == x {
					defaultValue := getDefaultValue(t)
					if defaultValue != "undefined" {
						return fmt.Sprintf("if s.%s != nil {\n    *s.%s = %s\n}", field.Names[0].Name, field.Names[0].Name, defaultValue)
					}
				}
			}
			return fmt.Sprintf("*s.%s = %s{}", field.Names[0].Name, x)
		}

	case *ast.SelectorExpr:
		sel := v.Sel.Name
		x := v.X.(*ast.Ident).Name
		return fmt.Sprintf("s.%s = %s.%s{}", field.Names[0].Name, x, sel)
	case *ast.MapType:
		return fmt.Sprintf("clear(s.%s)", field.Names[0].Name)
	case *ast.ChanType:
		return fmt.Sprintf("s.%s = nil", field.Names[0].Name)
	case *ast.ArrayType:
		return fmt.Sprintf("s.%s = s.%s[:0]", field.Names[0].Name, field.Names[0].Name)
	}
	return "undefined"
}

// getDefaultValue generates zero value according to a field type.
func getDefaultValue(typeName string) string {
	switch typeName {
	case "bool":
		return "false"
	case "string":
		return "\"\""
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "byte":
		return "0"
	case "float32", "float64":
		return "0.0"
	case "interface{}", "error":
		return "nil"
	}
	return ""
}

// createFile generates new file in a package with structs with the comment `// generate:reset`.
func createFile(dir, pkgName string, structs []StructInfo) error {
	data := TemplateData{
		PackageName: pkgName,
		Structs:     structs,
	}

	tmpl, err := template.New("reset").Parse(resetTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse resetTemplate: %v", err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, data)
	if err != nil {
		return fmt.Errorf("failed to execute template: %v", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		formatted = buf.Bytes()
	}

	outputPath := filepath.Join(dir, "reset.gen.go")
	err = os.WriteFile(outputPath, formatted, 0644)
	if err != nil {
		return fmt.Errorf("failed to write file %s: %v", outputPath, err)
	}
	fmt.Printf("file successfully created - %s\n", outputPath)
	return nil
}
