package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type FieldInfo struct {
	Name         string
	DefaultValue string
}

type StructInfo struct {
	PackageName string
	StructName  string
	Fields      []FieldInfo
}

type TemplateData struct {
	PackageName string
	Structs     []StructInfo
}

const resetTemplate = `// Code generated by reset.go; DO NOT EDIT.

package {{.PackageName}}

{{range .Structs}}
func (s *{{.StructName}}) Reset() {
	{{- range .Fields}}
	{{.DefaultValue}}
	{{- end}}
}
{{end}}
`

func main() {
	absDirPath, err := filepath.Abs("./internal/audit")
	if err != nil {
		log.Fatal(fmt.Errorf("failed to get absolute path: %v\n", err))
	}

	if _, err = os.Stat(absDirPath); os.IsNotExist(err) {
		log.Fatal(fmt.Errorf("directory does not exist: %s\n", absDirPath))
	}

	err = processDirectory(absDirPath)
	if err != nil {
		log.Fatal(fmt.Errorf("error: %v\n", err))
	}
}

// processDirectory goes through .go files to
func processDirectory(dir string) error {
	var result []StructInfo
	var pkgName string
	var pathToWrite string

	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			//log.Printf("failed to walk through directory: %s, err: %v\n", path, err)
			return fmt.Errorf("failed to walk through directory: %s, err: %v\n", path, err)
		}

		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			log.Printf("failed to read file: %s,  err: %v\n", path, err)
			return nil
		}
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, content, parser.ParseComments)
		if err != nil {
			log.Printf("Failed to parse file: %s, err: %v\n", path, err)
			return nil
		}

		if file.Name != nil {
			if pkgName != file.Name.Name {
				if len(result) > 0 {
					err = createFile(pathToWrite, pkgName, result)
					if err != nil {
						//log.Printf("failed to create file: %s, err: %v\n", dir, err)
						return fmt.Errorf("failed to create file: %s, err: %v\n", dir, err)
					}
				}
				result = []StructInfo{}
			}
			pkgName = file.Name.Name
			splitDir := strings.Split(path, "/")
			pathToWrite = strings.Join(splitDir[0:len(splitDir)-1], "/")
		}

		fileStructs := lookForStructs(file)
		if len(fileStructs) > 0 {
			for _, s := range fileStructs {
				s.PackageName = file.Name.Name
				result = append(result, s)
			}
		}
		return nil
	})

	if err != nil {
		//log.Printf("failed to walk through files error: %v\n", err)
		return fmt.Errorf("failed to walk through files error: %v\n", err)
	}

	if len(result) != 0 {
		return createFile(dir, pkgName, result)
	}
	return nil
}

// lookForStructs search for structs with the comment `// generate:reset`
func lookForStructs(file *ast.File) []StructInfo {
	var structs []StructInfo

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			if genDecl.Doc != nil {
				for _, comment := range genDecl.Doc.List {
					if comment.Text == "// generate:reset" {
						var fields []FieldInfo
						if structType.Fields != nil && structType.Fields.List != nil {
							for _, field := range structType.Fields.List {
								for _, name := range field.Names {
									defaultValue := getDefaultValue(field)
									fields = append(fields, FieldInfo{
										Name:         name.Name,
										DefaultValue: defaultValue,
									})
								}
							}
						}
						structs = append(structs, StructInfo{
							StructName: genDecl.Specs[0].(*ast.TypeSpec).Name.Name,
							Fields:     fields,
						})
						break
					}
				}
			}
		}
	}

	return structs
}

// getDefaultValue generates zero value according to a field type.
func getDefaultValue(field *ast.Field) string {
	var typeName string
	switch v := field.Type.(type) {
	case *ast.Ident:
		typeName = v.Name
	case *ast.StarExpr:
		switch v.X.(type) {
		case *ast.SelectorExpr:
			sel := v.X.(*ast.SelectorExpr).Sel.Name
			x := v.X.(*ast.SelectorExpr).X.(*ast.Ident).Name
			return fmt.Sprintf("if s.%s != nil {\n    *s.%s = %s.%s{}}", field.Names[0].Name, field.Names[0].Name, x, sel)
		case *ast.Ident:
			x := v.X.(*ast.Ident).Name
			stmt := fmt.Sprintf("if s.%s != nil {\n    v := reflect.ValueOf(s.%s)\n    method := v.MethodByName(\"Reset\")\n    if method.IsValid() {        method.Call(nil)\n        return\n    } else {\n        s.%s = &%s{}\n    }}", field.Names[0].Name, field.Names[0].Name, field.Names[0].Name, x)
			return stmt
		}
	case *ast.SelectorExpr:
		sel := v.Sel.Name
		x := v.X.(*ast.Ident).Name
		return fmt.Sprintf("s.%s = %s.%s{}", field.Names[0].Name, x, sel)
	case *ast.MapType:
		return fmt.Sprintf("clear(s.%s)", field.Names[0].Name)
	case *ast.ChanType:
		return fmt.Sprintf("s.%s = nil", field.Names[0].Name)
	}

	switch typeName {
	case "bool":
		return fmt.Sprintf("s.%s = false", field.Names[0].Name)
	case "string":
		return fmt.Sprintf("s.%s = \"\"", field.Names[0].Name)
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "byte":
		return fmt.Sprintf("s.%s = 0", field.Names[0].Name)
	case "float32", "float64":
		return fmt.Sprintf("s.%s = 0.0", field.Names[0].Name)
	case "interface{}", "error":
		return fmt.Sprintf("s.%s = nil", field.Names[0].Name)
	}
	return fmt.Sprintf("s.%s = \"\"", field.Names[0].Name)
}

// createFile creates a file in a package with structs with the comment `// generate:reset`.
func createFile(dir, pkgName string, structs []StructInfo) error {
	data := TemplateData{
		PackageName: pkgName,
		Structs:     structs,
	}

	tmpl, err := template.New("reset").Parse(resetTemplate)
	if err != nil {
		log.Printf("failed to parse resetTemplate: %v", err)
		return fmt.Errorf("failed to parse resetTemplate: %v", err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, data)
	if err != nil {
		log.Printf("failed to execute template: %v", err)
		return fmt.Errorf("failed to execute template: %v", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		formatted = buf.Bytes()
	}

	outputPath := filepath.Join(dir, "reset.gen.go")
	err = os.WriteFile(outputPath, formatted, 0644)
	if err != nil {
		log.Printf("failed to write file %s: %v", outputPath, err)
		return fmt.Errorf("failed to write file %s: %v", outputPath, err)
	}
	fmt.Printf("file successfully created - %s\n", outputPath)
	return nil
}
