// Code generated by reset.go; DO NOT EDIT.

package audit

import (
	"net/http"
	"os"
)

func (s *AuditWriter) Reset() {
	if s.file != nil {
		*s.file = os.File{}
	}
}

func (s *HTTPSink) Reset() {
	if s.client != nil {
		*s.client = http.Client{}
	}
}
